application: app_id
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries: 
- name: jinja2
  version: latest

handlers:
- url: /static/font
  static_dir: static/font

- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/img
  static_dir: static/img

- url: .*
  script: main.py

builtins:
- remote_api: on
- appstats: on
- deferred: on

